import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-100">
        <header className="bg-blue-500 text-white p-4">
          <nav className="flex space-x-4">
            <a href="/">Home</a>
            <a href="/rates">Rates</a>
            {/* <a href="/" className="hover:underline">Home</a>
            <a href="/rates" className="hover:underline">Rates</a> */}
          </nav>
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}

